// ✅ THIS is the file to deploy — paste it into the Val Town editor,
// or `vt push` from this directory.
//
// Generated by `npm run build:val`; do not edit. Source lives in src/.
// Every module is inlined, so there are no relative imports for Deno to
// chase — which is why src/val.ts cannot be deployed directly.

// src/val.ts
import { blob } from "https://esm.town/v/std/blob";
import { email } from "https://esm.town/v/std/email";

// src/parse.ts
import { extractText, getDocumentProxy } from "npm:unpdf";
var MONTHS = {
  Jan: "January",
  Feb: "February",
  Mar: "March",
  Apr: "April",
  May: "May",
  Jun: "June",
  Jul: "July",
  Aug: "August",
  Sep: "September",
  Oct: "October",
  Nov: "November",
  Dec: "December"
};
var AMOUNT_LINE = /^(\()?\$([\d,]+\.\d{2})(\))?$/;
function parseAmountCents(line) {
  const match = AMOUNT_LINE.exec(line.trim());
  if (!match) return null;
  const [, open, digits, close] = match;
  if (Boolean(open) !== Boolean(close)) return null;
  const cents = Math.round(Number(digits.replace(/,/g, "")) * 100);
  return open ? -cents : cents;
}
function toMonthLabel(statementDate) {
  const match = /^([A-Z][a-z]{2})\s+\d{1,2},\s*(\d{4})$/.exec(statementDate.trim());
  if (!match) throw new Error(`Unrecognised statement date: "${statementDate}"`);
  const month = MONTHS[match[1]];
  if (!month) throw new Error(`Unrecognised month in statement date: "${statementDate}"`);
  return `${month} ${match[2]}`;
}
function findStatementDate(pages) {
  for (const page of pages) {
    const match = /monthly statement for\s+([A-Z][a-z]{2}\s+\d{1,2},\s*\d{4})/.exec(page);
    if (match) return match[1].replace(/\s+/g, " ");
  }
  throw new Error(
    `No "monthly statement for <date>" line found. Is this a Google Fi statement?`
  );
}
function findMemberTable(pages) {
  for (const page of pages) {
    const table = readMemberTable(page);
    if (table) return table;
  }
  throw new Error(
    "No per-member table found. It is normally the last block on page 2, ending with a bare 'Total' line followed by the amount."
  );
}
function readMemberTable(page) {
  const lines = page.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
  const last = lines.length - 1;
  const totalCents = parseAmountCents(lines[last] ?? "");
  if (totalCents === null || lines[last - 1] !== "Total") return null;
  const entries = [];
  for (let i = last - 2; i >= 1; i -= 2) {
    const cents = parseAmountCents(lines[i]);
    if (cents === null) break;
    const name = lines[i - 1];
    if (name === "Total" || parseAmountCents(name) !== null) break;
    entries.push([name, cents]);
  }
  if (entries.length < 2) return null;
  entries.reverse();
  const summed = entries.reduce((sum, [, cents]) => sum + cents, 0);
  if (summed !== totalCents) {
    throw new Error(
      `Per-member amounts sum to ${(summed / 100).toFixed(2)} but the table total is ${(totalCents / 100).toFixed(2)}. The PDF was misread \u2014 refusing to guess.`
    );
  }
  return {
    people: Object.fromEntries(entries.map(([name, cents]) => [name, cents / 100])),
    totalCents
  };
}
function parseStatementText(pages) {
  const statementDate = findStatementDate(pages);
  const { people, totalCents } = findMemberTable(pages);
  return {
    statementDate,
    month: toMonthLabel(statementDate),
    people,
    total: totalCents / 100
  };
}
async function extractPdfPages(bytes) {
  const pdf = await getDocumentProxy(bytes);
  const { text } = await extractText(pdf, { mergePages: false });
  return text;
}
async function parseStatementPdf(bytes) {
  return parseStatementText(await extractPdfPages(bytes));
}

// src/split.ts
function toCents(dollars) {
  if (!Number.isFinite(dollars)) {
    throw new Error(`Not a number: ${dollars}`);
  }
  return Math.round(dollars * 100);
}
function formatCents(cents) {
  const sign = cents < 0 ? "-" : "";
  const abs = Math.abs(cents);
  return `${sign}$${Math.floor(abs / 100)}.${String(abs % 100).padStart(2, "0")}`;
}
function computeShares(bill, config) {
  const owners = config.people.filter((p) => p.isOwner);
  if (owners.length !== 1) {
    throw new Error(
      `Config needs exactly one person with "isOwner": true, found ${owners.length}.`
    );
  }
  const unknown = Object.keys(bill.people).filter(
    (name) => !config.people.some((p) => p.name === name)
  );
  if (unknown.length > 0) {
    throw new Error(
      `Statement lists people missing from config: ${unknown.join(", ")}. Names must match the statement exactly.`
    );
  }
  const missing = config.people.filter((p) => !(p.name in bill.people));
  if (missing.length > 0) {
    throw new Error(
      `Config has people with no amount on this statement: ${missing.map((p) => p.name).join(", ")}`
    );
  }
  const shares = config.people.map((person) => ({
    name: person.name,
    venmo: person.venmo,
    isOwner: person.isOwner === true,
    totalCents: toCents(bill.people[person.name] ?? 0)
  }));
  if (bill.total !== void 0) {
    const expected = toCents(bill.total);
    const actual = shares.reduce((sum, s) => sum + s.totalCents, 0);
    if (expected !== actual) {
      throw new Error(
        `Per-person amounts sum to ${formatCents(actual)} but the statement total is ${formatCents(expected)} (off by ${formatCents(actual - expected)}). Something was misread from the PDF.`
      );
    }
  }
  return shares;
}
function chargeable(shares) {
  return shares.filter((s) => !s.isOwner && s.totalCents > 0);
}

// src/changes.ts
function diffAmounts(previous, current) {
  if (!previous) return [];
  const names = [.../* @__PURE__ */ new Set([...Object.keys(previous), ...Object.keys(current)])];
  const changes = [];
  for (const name of names) {
    const before = previous[name];
    const after = current[name];
    if (before === void 0) {
      changes.push({ name, from: null, to: after });
    } else if (after === void 0) {
      changes.push({ name, from: before, to: null });
    } else if (toCents(before) !== toCents(after)) {
      changes.push({ name, from: before, to: after });
    }
  }
  return changes;
}
function describeChange(change) {
  const { name, from, to } = change;
  if (from === null) return `${name} added at $${to.toFixed(2)}`;
  if (to === null) return `${name} dropped off (was $${from.toFixed(2)})`;
  const direction = to > from ? "up" : "down";
  return `${name} ${direction} $${Math.abs(to - from).toFixed(2)} \u2014 $${from.toFixed(2)} \u2192 $${to.toFixed(2)}`;
}
function buildSubject(month, totalDollars, changes, isFirstRun) {
  const head = `Google Fi ${month} \u2014 $${totalDollars.toFixed(2)}`;
  if (isFirstRun) return `${head} \u2014 first run`;
  if (changes.length === 0) return head;
  const noun = changes.length === 1 ? "amount" : "amounts";
  return `${head} \u2014 ${changes.length} ${noun} changed`;
}

// src/links.ts
var NOTE_MAX = 200;
function encode(value) {
  return encodeURIComponent(value);
}
function normalizeUsername(username) {
  return username.trim().replace(/^@/, "");
}
function truncateNote(note) {
  return note.length <= NOTE_MAX ? note : `${note.slice(0, NOTE_MAX - 1)}\u2026`;
}
function amountFromCents(cents) {
  if (cents <= 0) throw new Error(`Charge amount must be positive, got ${cents} cents.`);
  return (cents / 100).toFixed(2);
}
function chargeLink(username, cents, note) {
  const users = (Array.isArray(username) ? username : [username]).map(normalizeUsername);
  if (users.length === 0) throw new Error("No Venmo usernames given.");
  if (users.some((u) => u === "")) throw new Error("Venmo username is empty.");
  const recipients = users.map(encode).join(",");
  const amount = amountFromCents(cents);
  const note_ = encode(truncateNote(note));
  return `https://venmo.com/payment-link?txn=charge&amount=${amount}&note=${note_}&recipients=${recipients}`;
}
function buildNote(template, month) {
  return template.replaceAll("{month}", month);
}
function listNames(names) {
  if (names.length <= 1) return names[0] ?? "";
  return `${names.slice(0, -1).join(", ")} and ${names.at(-1)}`;
}
function groupCharges(rows) {
  const buckets = /* @__PURE__ */ new Map();
  for (const row of rows) {
    const existing = buckets.get(row.share.totalCents);
    if (existing) existing.push(row);
    else buckets.set(row.share.totalCents, [row]);
  }
  return [...buckets.entries()].map(([totalCents, members]) => {
    const usernames = members.map((m) => m.username);
    const note = members[0].note;
    return {
      totalCents,
      amount: amountFromCents(totalCents),
      members,
      link: chargeLink(usernames, totalCents, note)
    };
  }).sort((a, b) => b.members.length - a.members.length || b.totalCents - a.totalCents);
}
function buildCharges(shares, noteTemplate, month) {
  const note = buildNote(noteTemplate, month);
  return shares.map((share) => {
    if (!share.venmo) {
      throw new Error(
        `${share.name} owes ${(share.totalCents / 100).toFixed(2)} but has no "venmo" username in config.`
      );
    }
    const username = normalizeUsername(share.venmo);
    return {
      share,
      username,
      amount: amountFromCents(share.totalCents),
      note,
      link: chargeLink(username, share.totalCents, note)
    };
  });
}

// src/email-render.ts
var BUTTON = "display:block;padding:14px 16px;border-radius:10px;background:#008cff;color:#ffffff;font-weight:600;text-decoration:none;text-align:center;font-size:16px";
var CARD = "border:1px solid #e3e6ea;border-radius:12px;padding:16px;margin:0 0 12px";
var MUTED = "color:#6b7280;font-size:13px;margin:0";
function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function renderEmailHtml(input) {
  const { month, charges, owner, billTotalCents, changes, isFirstRun } = input;
  const collecting = charges.reduce((sum, c) => sum + c.share.totalCents, 0);
  const banner = renderBanner(changes, isFirstRun);
  const groups = groupCharges(charges);
  const cards = groups.map((g) => {
    const names = listNames(g.members.map((m) => m.share.name));
    const handles = g.members.map((m) => `@${m.username}`).join(", ");
    const alone = g.members.length === 1;
    const fallback = alone ? "" : `<p style="${MUTED};margin-top:12px;text-align:center">One at a time: ${g.members.map(
      (m) => `<a href="${escapeHtml(m.link)}" style="color:#6b7280">${escapeHtml(m.share.name)}</a>`
    ).join(" \xB7 ")}</p>`;
    return `
      <div style="${CARD}">
        <p style="margin:0 0 4px;font-weight:600;font-size:16px">${escapeHtml(names)}</p>
        <p style="${MUTED};margin-bottom:14px">${escapeHtml(handles)}</p>
        <a href="${escapeHtml(g.link)}" style="${BUTTON}">Request $${escapeHtml(g.amount)}${alone ? "" : ` from ${g.members.length}`}</a>
        ${fallback}
      </div>`;
  }).join("");
  const tapCount = groups.length === 1 ? "one tap" : `${groups.length} taps`;
  return `<!doctype html>
<html>
<body style="margin:0;padding:24px 16px;background:#f6f7f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;color:#14161a">
  <div style="max-width:520px;margin:0 auto">
    <h1 style="font-size:20px;margin:0 0 4px">Google Fi \u2014 ${escapeHtml(month)}</h1>
    <p style="${MUTED};margin-bottom:20px">
      Bill ${formatCents(billTotalCents)} \xB7 collecting ${formatCents(collecting)} \xB7
      your share ${formatCents(owner.totalCents)}
    </p>
    ${banner}
    ${cards}
    <p style="${MUTED};text-align:center;margin-top:24px">
      ${tapCount} to collect ${formatCents(collecting)}. Each button opens Venmo with the
      request prefilled \u2014 nothing is sent until you confirm in the app.
    </p>
  </div>
</body>
</html>`;
}
function renderBanner(changes, isFirstRun) {
  if (isFirstRun) {
    return `<div style="${CARD};background:#f2f4f7;border-color:#d8dce2">
      <p style="margin:0;font-size:14px">
        First run \u2014 nothing to compare against yet. From next month you'll see any amount that moved.
      </p>
    </div>`;
  }
  if (changes.length === 0) return "";
  const items = changes.map((c) => `<li style="margin:0 0 4px">${escapeHtml(describeChange(c))}</li>`).join("");
  return `<div style="${CARD};background:#fff8e6;border-color:#f0d999">
    <p style="margin:0 0 8px;font-weight:600;font-size:14px">Amounts changed since last month</p>
    <ul style="margin:0;padding-left:20px;font-size:14px">${items}</ul>
  </div>`;
}
function renderEmailText(input) {
  const { month, charges, owner, billTotalCents, changes, isFirstRun } = input;
  const collecting = charges.reduce((sum, c) => sum + c.share.totalCents, 0);
  const lines = [
    `Google Fi \u2014 ${month}`,
    `Bill ${formatCents(billTotalCents)} \xB7 collecting ${formatCents(collecting)} \xB7 your share ${formatCents(owner.totalCents)}`,
    ""
  ];
  if (isFirstRun) {
    lines.push("First run \u2014 nothing to compare against yet.", "");
  } else if (changes.length > 0) {
    lines.push("Amounts changed since last month:");
    lines.push(...changes.map((c) => `  - ${describeChange(c)}`));
    lines.push("");
  }
  for (const g of groupCharges(charges)) {
    const alone = g.members.length === 1;
    lines.push(`${listNames(g.members.map((m) => m.share.name))} \u2014 $${g.amount}${alone ? "" : " each"}`);
    lines.push(`  ${g.link}`);
    if (!alone) {
      lines.push("  One at a time:");
      lines.push(...g.members.map((m) => `    ${m.share.name}: ${m.link}`));
    }
    lines.push("");
  }
  lines.push("Each link opens Venmo with the request prefilled. Nothing is sent until you confirm.");
  return lines.join("\n");
}

// src/history.ts
var KEEP = 2;
function updateHistory(history, current) {
  const records = history ?? [];
  const isRepeat = records.some((r) => r.statementDate === current.statementDate);
  const baseline = records.find((r) => r.statementDate !== current.statementDate);
  return {
    baseline,
    isRepeat,
    next: isRepeat ? records : [current, ...records].slice(0, KEEP)
  };
}

// src/process.ts
var FORWARDING_CONFIRMATION_SENDER = "forwarding-noreply@google.com";
function addressOf(from) {
  const angled = /<([^>]+)>/.exec(from);
  return (angled?.[1] ?? from).trim().toLowerCase();
}
function findPdf(attachments) {
  const pdfs = attachments.filter(
    (a) => a.type === "application/pdf" || /\.pdf$/i.test(a.name)
  );
  if (pdfs.length === 0) {
    throw new Error(
      "No PDF attachment. The Fi statement carries the per-member breakdown as an attachment; the email body has only the total."
    );
  }
  if (pdfs.length > 1) {
    throw new Error(`Expected one PDF attachment, found ${pdfs.length}.`);
  }
  return pdfs[0];
}
async function processStatement(message, deps2) {
  const sender = addressOf(message.from);
  if (sender === FORWARDING_CONFIRMATION_SENDER) {
    await deps2.send({
      subject: "google-fi-group-repay: Gmail forwarding confirmation",
      text: [
        "Gmail sent a forwarding confirmation to the google-fi-group-repay address.",
        "Copy the code or link below into Gmail's forwarding settings.",
        "",
        message.text ?? "(no text body)"
      ].join("\n")
    });
    return { status: "confirmation" };
  }
  if (!deps2.allowedSenders.includes(sender)) {
    return { status: "ignored", reason: `sender ${sender} is not allowed` };
  }
  const pdf = findPdf(message.attachments);
  const { statementDate, ...bill } = await deps2.parsePdf(await pdf.bytes());
  const shares = computeShares(bill, deps2.config);
  const owner = shares.find((s) => s.isOwner);
  const charges = buildCharges(chargeable(shares), deps2.config.noteTemplate, bill.month);
  const record = {
    statementDate,
    people: bill.people,
    total: bill.total
  };
  const { baseline, isRepeat, next } = updateHistory(await deps2.getHistory(), record);
  const changes = diffAmounts(baseline?.people, bill.people);
  const isFirstRun = baseline === void 0;
  const input = {
    month: bill.month,
    charges,
    owner,
    billTotalCents: shares.reduce((sum, s) => sum + s.totalCents, 0),
    changes,
    isFirstRun
  };
  const subject = buildSubject(bill.month, bill.total, changes, isFirstRun);
  await deps2.send({
    subject: isRepeat ? `${subject} (repeat)` : subject,
    html: renderEmailHtml(input),
    text: renderEmailText(input)
  });
  if (!isRepeat) await deps2.saveHistory(next);
  return { status: "sent", month: bill.month, charged: charges.length, isRepeat };
}

// src/val.ts
var BLOB_KEY = "fi-group-repay:statements";
var DEFAULT_SENDERS = ["payments-noreply@google.com"];
function allowedSenders() {
  const configured = Deno.env.get("FI_GROUP_REPAY_ALLOWED_SENDERS");
  if (!configured) return DEFAULT_SENDERS;
  return configured.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
}
function loadConfig() {
  const raw = Deno.env.get("FI_GROUP_REPAY_CONFIG");
  if (!raw) {
    throw new Error("FI_GROUP_REPAY_CONFIG is not set. It should hold the contents of config.json.");
  }
  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(
      `FI_GROUP_REPAY_CONFIG is not valid JSON: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
function adapt(message) {
  return {
    from: message.from,
    subject: message.subject,
    text: message.text,
    attachments: message.attachments.map((file) => ({
      name: file.name,
      type: file.type,
      bytes: async () => new Uint8Array(await file.arrayBuffer())
    }))
  };
}
function deps() {
  return {
    config: loadConfig(),
    allowedSenders: allowedSenders(),
    parsePdf: parseStatementPdf,
    getHistory: () => blob.getJSON(BLOB_KEY),
    saveHistory: (next) => blob.setJSON(BLOB_KEY, next),
    send: async ({ subject, text, html }) => {
      await email(html ? { subject, text, html } : { subject, text });
    }
  };
}
async function reportFailure(message, error) {
  const detail = error instanceof Error ? error.stack ?? error.message : String(error);
  console.error(detail);
  await email({
    subject: "google-fi-group-repay failed to process a Google Fi statement",
    text: [
      "google-fi-group-repay could not turn the attached statement into charge links.",
      "",
      `From:    ${message.from}`,
      `Subject: ${message.subject ?? "(none)"}`,
      `Files:   ${message.attachments.map((a) => a.name).join(", ") || "(none)"}`,
      "",
      detail,
      "",
      "The bill still needs collecting \u2014 open the statement and request manually."
    ].join("\n")
  });
}
async function handleStatement(message) {
  try {
    const result = await processStatement(adapt(message), deps());
    console.log(JSON.stringify(result));
  } catch (error) {
    await reportFailure(message, error);
  }
}
export {
  handleStatement as default
};
