import { readFile, writeFile } from "node:fs/promises";

const IN = "config.json";
const OUT = "config.env";

const config = JSON.parse(await readFile(IN, "utf8"));

// Fail here rather than on the val, where a bad handle means a wrong request.
const people = config.people ?? [];
const owners = people.filter((p) => p.isOwner);
if (owners.length !== 1) {
  throw new Error(`${IN} needs exactly one person with "isOwner": true, found ${owners.length}.`);
}
// Must match what config.example.json actually ships. It previously looked
// only for FILL-ME-IN, which appears nowhere in the example, so the guard
// never fired on the file it exists to catch.
const PLACEHOLDER_HANDLE = /^(FILL-ME-IN|friend-\w+-handle|your-handle)$/i;
const unset = people.filter(
  (p) => !p.isOwner && (!p.venmo || PLACEHOLDER_HANDLE.test(p.venmo.trim())),
);
if (unset.length > 0) {
  throw new Error(
    `${IN} still has placeholder Venmo handles: ${unset.map((p) => p.name).join(", ")}`,
  );
}

// Who the val accepts statements from. Lives in config.json so there is still
// one file to edit, but ships as its own variable — the val reads it separately.
const { allowedSenders = ["payments-noreply@google.com"], ...valConfig } = config;
if (!Array.isArray(allowedSenders) || allowedSenders.length === 0) {
  throw new Error(`${IN}: "allowedSenders" must be a non-empty array of addresses.`);
}

// The example ships a placeholder so the hand-forwarding option is visible.
// Every address here is one the val accepts statements from, so shipping an
// unedited one to a live val has to be impossible.
const PLACEHOLDER_SENDER = /^your-email@example\.com$/i;
const placeholderSenders = allowedSenders.filter((s) =>
  PLACEHOLDER_SENDER.test(String(s).trim()),
);
if (placeholderSenders.length > 0) {
  throw new Error(
    `${IN}: "allowedSenders" still contains the placeholder ${placeholderSenders.join(", ")}. ` +
      `Replace it with your own address, or remove it if you only use Gmail's ` +
      `automatic forwarding.`,
  );
}

// Minified onto one line: dotenv format has no agreed multi-line syntax, and a
// value broken across lines is the classic way one of these silently truncates.
const value = JSON.stringify(valConfig);

// Single quotes so the JSON's own double quotes pass through untouched. There
// is no portable way to escape a single quote inside a single-quoted dotenv
// value, so an apostrophe in a name has to be handled by hand.
const senders = allowedSenders.map((s) => String(s).trim().toLowerCase()).join(",");

if (value.includes("'") || senders.includes("'")) {
  throw new Error(
    `${IN} contains an apostrophe, which cannot be quoted safely in ${OUT}. ` +
      `Set FI_GROUP_REPAY_CONFIG directly in the Val Town UI instead.`,
  );
}

const env = `# Generated by \`npm run build:env\` from ${IN} — do not edit.
# Import into Val Town: val settings -> Environment variables -> import ${OUT}
#
# ${IN} is the source of truth. After changing a Venmo handle or the roster,
# re-run \`npm run build:env\` and re-import.

FI_GROUP_REPAY_CONFIG='${value}'

# Who the val accepts statements from. Set explicitly even though the code has a
# default, so Val Town doesn't warn about an unset variable on every run.
FI_GROUP_REPAY_ALLOWED_SENDERS='${senders}'
`;

await writeFile(OUT, env, "utf8");
console.log(`Wrote ${OUT} from ${IN} — ${people.length} people, ${value.length} chars of JSON.`);
console.log(`Accepting statements from: ${senders.split(",").join(", ")}`);
