import { readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const OUT = "valtown/main.ts";

await build({
  entryPoints: ["src/val.ts"],
  outfile: OUT,
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "neutral",
  // Val Town resolves these itself. Bundling pdf.js in would be pointless bulk.
  external: ["https://esm.town/*", "unpdf"],
});

const header = `// ✅ THIS is the file to deploy — paste it into the Val Town editor,
// or \`vt push\` from this directory.
//
// Generated by \`npm run build:val\`; do not edit. Source lives in src/.
// Every module is inlined, so there are no relative imports for Deno to
// chase — which is why src/val.ts cannot be deployed directly.

`;

// esbuild leaves the bare specifier; Deno needs the npm: prefix to resolve it.
const bundled = (await readFile(OUT, "utf8")).replace(/(from\s*)"unpdf"/g, '$1"npm:unpdf"');

if (!bundled.includes('"npm:unpdf"')) {
  throw new Error("unpdf import was not rewritten for Deno — check the bundle output.");
}

await writeFile(OUT, header + bundled, "utf8");

console.log(`Wrote ${OUT} (${((header.length + bundled.length) / 1024) | 0} KB)`);
console.log(`Deploy this file — not src/val.ts.`);
if (process.platform === "darwin") {
  console.log(`Copy it with:  pbcopy < ${OUT}`);
}
